cc_library(
    name = "core",
    srcs = glob([
        "*.cc",
        "*.h",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        "//:taco",
        "//src/config:arch_config",
        "//src/config:event",
    ],
)
